### ISSUE TITLE
Switch to Github Actions

### ISSUE THREAD

**Issue by josegonzalez** [robxu9/bash-static#4]
Seems like travis is not setup for PRs, but would be great to switch to Github Actions.

These actions may help:

- https://github.com/actions/create-release
- https://github.com/actions/upload-release-asset

**Comment by robxu9** [comment]
Yeah, I'll need to switch them since travis-ci.org is being deprecated... I'll see if I can get around to it this week.

**Comment by robxu9** [comment]
Eh, I was waiting for a mass rebuild to complete so I ended up getting this done while waiting:

https://github.com/robxu9/bash-static/releases/tag/5.1-actions-1
